### ISSUE TITLE
Inefficient use of connection pools that leverage a `Connector`

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/genai-databases-retrieval-app#416]
The Cloud SQL and AlloyDB datastore providers could improve their use of connection pools, leading to more efficient quota and resource consumption.

https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/blob/69872805d55eb7332bf533417d44faf2f39b9687/retrieval_service/datastore/providers/cloudsql_postgres.py#L57-L73

The [`creator`](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.creator) argument (same for `async_creator`) for SQLAlchemy is called on each new database connection. This means that initializing a Cloud SQL or AlloyDB `Connector` object within the `get_conn` is creating a new Connector for each connection pool connection and not sharing a single `Connector` across all connections. 

For heavy usage this would lead to Cloud SQL or AlloyDB quotas being exhausted and for applications to begin to error.

A more efficient use would be to create a single `Connector` outside of `get_conn` so that it can be shared across all connections.

**Comment by jackwotherspoon** [comment]
@anubhav756 Cloud SQL MySQL seems to have been missed, it also needs to be fixed

**Comment by anubhav756** [comment]
> @anubhav756 Cloud SQL MySQL seems to have been missed, it also needs to be fixed
> 
> https://github.com/GoogleCloudPlatform/genai-databases-retrieval-app/blob/2b05739b0eb761738cc8db06d76f64ad7d199a2e/retrieval_service/datastore/providers/cloudsql_mysql.py#L55-L67

Missed it. Thanks for pointing that out Jack!
