### ISSUE TITLE
Amenity Queries Return "Sorry, we couldn't answer your question 😢"

### ISSUE THREAD

**Issue by keolo** [GoogleCloudPlatform/genai-databases-retrieval-app#513]
## Description

Hi, thank you for creating this repo!

I've successfully deployed the demo application after completing the [Create Generative AI Apps on Google Cloud](https://www.cloudskillsboost.google/paths/1282/course_templates/1120) course.

While queries related to flight information seem to work correctly, queries regarding airport amenities consistently return the message "Sorry, we couldn't answer your question 😢".

## Replication

1. Deploy the application as described in the course.
2. Use the chat interface to ask the following questions:
    *   "Are there any Luxury shops?"
    *   "Where can I find a gift?"
    *   "Where can I find coffee near gate A6?"

## Expected Behavior

The application should return relevant information about airport amenities based on the query. For example, for the query "Where can I find coffee near gate A6?", the application should return a list of coffee shops near gate A6.

## Actual Behavior

The application returns the message "Sorry, we couldn't answer your question 😢" for all amenity-related queries.

## Screenshots

<img width="857" alt="Screenshot 2024-11-24 at 10 11 36 AM" src="https://github.com/user-attachments/assets/9e91cd51-3b44-4eae-ae69-243d7a7f72e3">

## Additional Context

* Course followed: [Create Generative AI Apps on Google Cloud](https://www.cloudskillsboost.google/paths/1282/course_templates/1120)
* Flight data queries seem to function correctly
* The issue appears to be specific to queries related to amenities

## Possible Causes/Debugging Steps Taken So Far

I have checked the following without success:

* Verified data ingestion and AlloyDB population (amenity data appears to be present)
* Reviewed the agent/tool configurations, but haven't spotted any obvious misconfigurations

Any guidance on how to troubleshoot this issue further would be greatly appreciated, thank you!

**Comment by Yuan325** [comment]
Hi, thanks for using the app!

Here's a couple of debugging steps:
1. Have you tried turning on DEBUG by `export DEBUG=true` before running `python run_app.py`? Can you please copy the terminal output when you run amenities-related question?
2. In GCP dashboard under the cloud run service that you deployed (Cloud Run > retrieval_service > logs), are there any errors?

With this, we should be able to determine if the error is within the LLM app itself, or the retrieval service.

**Comment by keolo** [comment]
Thanks @Yuan325!

If I'm reading it right, it looks like I'm getting a 500 error in the retrieval-service for the Search Amenities action.

<img width="1491" alt="llm-chain" src="https://github.com/user-attachments/assets/f2492e70-c7f8-4f8d-a1b8-e026ec4e8b74">


https://github.com/user-attachments/assets/fb5e7578-cc61-4797-a39a-bea6a3fc5c06

```
GET 500 Python/3.11 aiohttp/3.11.7 https://retrieval-service-31607603582.us-west1.run.app/amenities/search?top_k=5&query=restaurants+near+gate+A34+at+SFO
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
```

I'm not seeing any other errors in the logs and I wonder if this might be some issue with a gRPC config?

Appreciate the help and please lmk if there's anything else I can check!

**Comment by Yuan325** [comment]
Are you able to make policy related queries? (e.g. How many checked luggage can I bring?). I'm suspecting this is an issue with accessing the embedding model.

The flights query does not uses the embedding model since its a structured data. It queries directly using SQL statements.
Only amenities or policies related query uses the embedding model since they will need to convert user query into embeddings, and then run similarity search to retrieve the answer.

**Comment by keolo** [comment]
Thanks for clarifying. It does seem to be pointing to the the embedding model since the policies query also fails with the same error.

```
Project `607844928719` is not allowed to use Publisher Model `projects/qwiklabs-gcp-03-93b7ae73b563/locations/us-central1/publishers/google/models/textembedding-gecko@001`
```

<img width="907" alt="policies-query" src="https://github.com/user-attachments/assets/77883bfb-a61a-4f29-b768-c2ddaec1f5a4">

Do you think there's a permission issue with the service account created in "Task 5. Create a service account for the retrieval service" (I'm not sure how to grant access to the Publisher Model)?

It feels like we're getting close, and as always, I appreciate the guidance!

**Comment by anubhav756** [comment]
#519 updates the text embedding model to the latest one, so you should now be able to run without any issues.

Please let me know if you are still facing the issue. Thanks!

Just wanted to give you an update! #519 upgrades the text embedding model to the [latest and greatest](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions#embeddings_stable_model_versions) (`text-embedding-005`), which should hopefully resolve this issue.

Could you please give it another try and let me know if you're still seeing any errors?

Appreciate your patience and feedback.

**Comment by keolo** [comment]
Thanks @anubhav756 and @Yuan325, it looks like upgrading the embedding model worked!

<img width="1512" alt="Screenshot 2024-12-10 at 8 25 27 PM" src="https://github.com/user-attachments/assets/807eefa3-3938-4f72-9858-411f26e783ad">
